#
# These are the same as the defaults.
#
quarkus.package.jar.type=fast-jar
quarkus.http.port=8080
%dev.quarkus.http.port=5050
#
# Container image build
#
quarkus.container-image.build=true
quarkus.container-image.group=caf
quarkus.container-image.name=caf-rest
#
# Endpoint URL for the microservice
#
quarkus.rest-client."io.github.tylerhackett.caf.rest.IThumbnailResource".url=http://localhost:4040/
%prod.quarkus.rest-client."io.github.tylerhackett.caf.rest.IThumbnailResource".url=http://caf-thumbnail:8080/
#
# JWT configuration for client
#
kc.hostname=localhost
kc.hostname.port=9090
quarkus.oidc.auth-server-url=http://${KC_HOSTNAME:localhost}:9090/realms/caf-realm
quarkus.oidc.client-id=caf-rest
%dev.quarkus.oidc.credentials.secret=${CAF_REST_CLIENT_SECRET}
quarkus.oidc.application-type=service
quarkus.oidc.roles.source=accesstoken
quarkus.oidc.roles.role-claim-path=resource_access/caf-rest/roles
%dev.smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.sign.key.location=file:/run/secrets/caf_rest_jwt_key
caf.jwt.issuer=http://${KC_HOSTNAME:localhost}:9090/realms/caf-realm
caf.jwt.audience=caf-thumbnail
#
# Configuration properties
#
caf.image.bucket=caf-images
caf.thumbnail.maxwidth=150
caf.thumbnail.maxheight=150
#
# JWT verification via MicroProfile JWT
#
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.tls.tls-disabled.trust-all=true
quarkus.tls.tls-disabled.hostname-verification-algorithm=NONE
quarkus.keycloak.devservices.enabled=false
