#
# Data source
#
quarkus.datasource.db-kind = postgresql
quarkus.datasource.jdbc.max-size = 14

%dev.quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/caf
%dev.quarkus.datasource.username=cafuser
%dev.quarkus.datasource.password=${DATABASE_PASSWORD}

%prod.quarkus.datasource.jdbc.url = jdbc:postgresql://caf-database:5432/caf

#
# Persistence unit that uses this datasource
#
# Use this the first time you deploy the database
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
# Use this if you don't want to lose all record of images when you deploy
# quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.packages=io.github.tylerhackett.caf.domain
quarkus.hibernate-orm.schema-management.create-schemas=true
#