%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/caf
%dev.quarkus.datasource.username=cafuser
%dev.quarkus.datasource.password=${DATABASE_PASSWORD}
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.max-size=14
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.packages=io.github.tylerhackett.caf.domain
quarkus.hibernate-orm.schema-management.create-schemas=true