#
# These are the same as the defaults.
#
quarkus.package.jar.type=fast-jar
quarkus.http.port=8080
%dev.quarkus.http.port=4040
#
# Container image build
#
quarkus.container-image.build=true
quarkus.container-image.group=caf
quarkus.container-image.name=caf-thumbnail
#
# Logging
#
quarkus.log.category."io.quarkus.smallrye.jwt".level=TRACE
quarkus.log.category."io.quarkus.oidc".level=TRACE
#
# JWT configuration for server
#
mp.jwt.verify.issuer=http://${KC_HOSTNAME:localhost}:9090/realms/caf-realm
mp.jwt.verify.audiences=caf-thumbnail
mp.jwt.verify.publickey.location=publicKey.pem
quarkus.native.resources.includes=publicKey.pem
quarkus.tls.tls-disabled.trust-all=true
quarkus.tls.tls-disabled.hostname-verification-algorithm=NONE

# Amazon S3 (see caf-webapp)
#
%dev.quarkus.s3.endpoint-override=http://localhost:4566
quarkus.s3.endpoint-override=http://s3local:4566
quarkus.s3.path-style-access=true
quarkus.s3.aws.region=us-east-1
%dev.quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.type=default
%dev.quarkus.s3.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY_ID}
%dev.quarkus.s3.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_ACCESS_KEY}
quarkus.s3.devservices.enabled=false

