%dev.quarkus.oidc.auth-server-url=http://localhost:9090/realms/caf-realm
%prod.quarkus.oidc.auth-server-url=https://keycloak:8543/realms/caf-realm
quarkus.oidc.client-id=caf-webapp
%dev.quarkus.oidc.credentials.secret=${CAF_WEBAPP_CLIENT_SECRET}
quarkus.oidc.application-type=web-app
quarkus.oidc.tls.verification=none
quarkus.oidc.roles.source=accesstoken
quarkus.keycloak.devservices.enabled=false
quarkus.keycloak.policy-enforcer.enabled=false

quarkus.s3.endpoint-override=http://s3.localhost:4566
quarkus.s3.path-style-access=true
quarkus.s3.aws.region=us-east-1
quarkus.s3.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY_ID}
quarkus.s3.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_ACCESS_KEY}
%dev.quarkus.s3.aws.credentials.type=static
%prod.quarkus.s3.aws.credentials.type=default
quarkus.s3.devservices.enabled=false

caf.image.bucket=caf-images
caf.image.type=image/jpeg
caf.image.ext=jpg
caf.image.url=http://s3.localhost:4566/%s/%s