#
# These are the same as the defaults.
#
quarkus.package.jar.type=fast-jar
quarkus.http.port=8080
#
# Container image build
#
quarkus.container-image.build=true
quarkus.container-image.group=caf
quarkus.container-image.name=caf-webapp
#
# Logging
#
quarkus.log.category."io.quarkus.smallrye.jwt".level=TRACE
quarkus.log.category."io.quarkus.oidc".level=TRACE
#
# Config properties
#
caf.image.bucket=caf-images
caf.image.type=image/jpeg
caf.image.ext=jpg
caf.image.url=http://localhost:4566/%s/%s
caf.image.region=us-east-1
#
# OIDC properties
#
quarkus.oidc.auth-server-url=http://${KC_HOSTNAME:localhost}:9090/realms/caf-realm
quarkus.oidc.client-id=caf-webapp
%dev.quarkus.oidc.credentials.secret=${CAF_WEBAPP_CLIENT_SECRET}
quarkus.oidc.application-type=web-app
quarkus.oidc.roles.source=accesstoken
quarkus.tls.tls-disabled.trust-all=true
quarkus.tls.tls-disabled.hostname-verification-algorithm=NONE
quarkus.keycloak.devservices.enabled=false

#
# Amazon S3
# https://docs.quarkiverse.io/quarkus-amazon-services/dev/amazon-s3.html
#
%dev.quarkus.s3.endpoint-override=http://localhost:4566
quarkus.s3.endpoint-override=http://s3local:4566
quarkus.s3.path-style-access=true
quarkus.s3.aws.region=us-east-1
%dev.quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.type=default
%dev.quarkus.s3.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY_ID}
%dev.quarkus.s3.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_ACCESS_KEY}
quarkus.s3.devservices.enabled=false

