<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>caf-service</artifactId>
	<packaging>jar</packaging>

	<parent>
		<groupId>io.github.tylerhackett</groupId>
		<artifactId>caf-root</artifactId>
		<version>1.0.0</version>
		<relativePath>../caf-root/pom.xml</relativePath>
	</parent>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-arc</artifactId>
		</dependency>

		<!-- https://quarkus.io/guides/security-keycloak-admin-client -->
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-keycloak-admin-rest-client</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-jackson</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-client-jackson</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-client-oidc-token-propagation </artifactId>
		</dependency>

		<dependency>
			<groupId>com.fasterxml.uuid</groupId>
			<artifactId>java-uuid-generator</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.tylerhackett</groupId>
			<artifactId>caf-service-client</artifactId>
		</dependency>
	</dependencies>
</project>
