caf.client.realm=caf-realm
caf.client.client-id=caf-webapp
caf.client.user-role=user
quarkus.keycloak.admin-client.enabled=true
%dev.quarkus.keycloak.admin-client.server-url=http://localhost:9090
quarkus.keycloak.admin-client.realm=master
quarkus.keycloak.admin-client.client-id=admin-cli
%dev.quarkus.keycloak.admin-client.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
quarkus.keycloak.admin-client.username=
quarkus.keycloak.admin-client.password=
quarkus.keycloak.admin-client.grant-type=client-credentials

