#
# Configure Keycloak admin client (for adding users)
#
quarkus.keycloak.admin-client.server-url=http://${KC_HOSTNAME:localhost}:9090
quarkus.keycloak.admin-client.realm=master
quarkus.keycloak.admin-client.client-id=admin-cli
quarkus.keycloak.admin-client.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET}
quarkus.keycloak.admin-client.grant-type=client_credentials
#
# Config properties
#
caf.client.realm=caf-realm
caf.client.client-id=caf-webapp
caf.client.user-role=user

#
# Endpoint URL for the images microservice
#
%dev.quarkus.rest-client."io.github.tylerhackett.caf.service.micro.IImageResource".url=http://localhost:5050/api
%dev.quarkus.rest-client."io.github.tylerhackett.caf.service.micro.IApprovalResource".url=http://localhost:5050/api
%dev.quarkus.rest-client."io.github.tylerhackett.caf.service.micro.IUserResource".url=http://localhost:5050/api
quarkus.rest-client."io.github.tylerhackett.caf.service.micro.IImageResource".url=http://caf-rest:8080/api
quarkus.rest-client."io.github.tylerhackett.caf.service.micro.IApprovalResource".url=http://caf-rest:8080/api
quarkus.rest-client."io.github.tylerhackett.caf.service.micro.IUserResource".url=http://caf-rest:8080/api
quarkus.rest-client."io.github.tylerhackett.caf.service.micro.IImageResource".tls-configuration-name=tls-disabled
quarkus.rest-client."io.github.tylerhackett.caf.service.micro.IApprovalResource".tls-configuration-name=tls-disabled
quarkus.rest-client."io.github.tylerhackett.caf.service.micro.IUserResource".tls-configuration-name=tls-disabled

#
# Configure token exchange for propagation to microservice
#
quarkus.oidc-client.auth-server-url=http://${KC_HOSTNAME:localhost}:9090/realms/caf-realm
quarkus.oidc-client.client-id=caf-webapp
%dev.quarkus.oidc-client.credentials.secret=${CAF_WEBAPP_CLIENT_SECRET}
quarkus.oidc-client.grant.type=exchange
quarkus.oidc-client.grant-options.exchange.audience=caf-rest
quarkus.oidc-client.grant-options.exchange.target_issuer=http://${KC_HOSTNAME:localhost}:9090/realms/caf-realm
quarkus.oidc-client.grant-options.exchange.requested_token_type=urn:ietf:params:oauth:token-type:access_token
quarkus.rest-client-oidc-token-propagation.exchange-token=true

caf.jwt.issuer=http://${KC_HOSTNAME:localhost}:9090/realms/caf-realm
caf.jwt.audience=caf-rest

#
# JWT signing key for calling thumbnail service
#
%dev.smallrye.jwt.sign.key.location=privateKey.pem
smallrye.jwt.sign.key.location=file:/run/secrets/caf_rest_jwt_key